name: Docker Image CI

on:
  push:
    branches: [ "master", "staging" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout 
        uses: actions/checkout@v1
      -
        name: Determine Docker Tags
        shell: bash
        run: |
          VERSION=$(grep -oP '(?<="version": ").*?(?=")' package.json)
          echo "Found version number: $VERSION"
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          echo "Found branch name: $BRANCH_NAME"
          if [ "$BRANCH_NAME" == "master" ]; then
             echo "Doing release deploy"
             echo "TAGS=aiguy110/tetris-battle:v${VERSION},aiguy110/tetris-battle:latest" > $GITHUB_ENV
          else
             echo "Doing staging deploy"
             echo "TAGS=aiguy110/tetris-battle:v${VERSION},aiguy110/tetris-battle:latest-staging" > $GITHUB_ENV
          fi
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TAGS }}
